trigger:
  - main

pool: Default

variables:
  - group: Nikhil-Shop-Sonar-Credentails

  - name: nodeVersion
    value: '22'
  
  - name: IMAGE_TAG
    value: 'v1.0.$(Build.BuildId)'
  
  - group: AWS-CREDENTIALS

stages:
  - stage: Build
    displayName: Buils stage
    jobs:
      - job: Build
        displayName:  Build Vite Application
        steps:

          - task: UseNode@01
            inputs:
              version:  $(nodeVersion)
            displayName:  Install Node.js

          - script: |
              node -v
              npm -v
            displayName: verify Node & NPM
          
          - script: |
              npm ci
            displayName: 'Install Dependencies'
          
          - script: |
              npm run build
            displayName:  'Build Project'
          
          - publish: dist
            artifact: vite-build
            displayName:  Publish Build Artifact
          
          - script: |
              npm run lint
            displayName: Run ESLint
          
          - task: SonarCloudPrepare@3
            displayName: Sonar Cloud Analysis
            inputs:
              SonarCloud: 'Sonar'
              organization: '$(Sonar-Organization)'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: '$(Sonar-Projectkey)'
              cliProjectName: '$(Sonar-Projectname)'
              cliSources: '.'
            
          - task: SonarCloudAnalyze@3
            displayName:  'Run SonarCloud Analysis'
          
          - task: SonarCloudPublish@3
            displayName:  'Publish Quality Gate'
            inputs:
              pollingTimeoutSec:  '300'

          - script: |
              docker compose -f docker-compose.yaml -p nikhil-shop down --rmi all
            displayName: "Stop and remove comtainers"

          - task: DockerCompose@1
            displayName: 'Docker Compose Up'
            inputs:
              dockerComposeFile:  '**/docker-compose.yaml'
              action:  'run services'
              detached: true
              buildImages: true
              projectName: 'nikhil-shop'
          
          - script: |
              aws sts get-caller-identity
            displayName: "Verify AWS Credentials"
            export AWS_ACCESS_KEY_ID:$(AWS_ACCESS_KEY_ID)
            export AWS_SECRET_ACCESS_KEY:$(AWS_SECRET_ACCESS_KEY)
            export AWS_DEFAULT_REGION:$(AWS_DEFAULT_REGION)
            


