trigger: none

pool: Default

parameters:
  - name: remove_image_container
    displayName: Stop and remove comtainers
    type: boolean
    default: true

  - name: docker_compose
    displayName: Docker Compose Up
    type: boolean
    default: true

  - name: image_tag
    displayName: Docker Image Tag
    type: string
    default: ""

variables:
  - group: Nikhil-Shop-Sonar-Credentails

  - name: nodeVersion
    value: "22"

  - name: IMAGE_TAG
    value: "v1.0.$(Build.BuildId)"

  - group: AWS-CREDENTIALS

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build Vite Application
        steps:
          - task: UseNode@01
            inputs:
              version: $(nodeVersion)
            displayName: Install Node.js

          - script: |
              node -v
              npm -v
            displayName: verify Node & NPM

          - script: |
              npm ci
            displayName: "Install Dependencies"

          - script: |
              npm run build
            displayName: "Build Project"

          - publish: dist
            artifact: vite-build
            displayName: Publish Build Artifact

          - script: |
              npm run lint
            displayName: Run ESLint

          - task: SonarCloudPrepare@3
            displayName: Sonar Cloud Analysis
            inputs:
              SonarCloud: "Sonar"
              organization: "$(Sonar-Organization)"
              scannerMode: "CLI"
              configMode: "manual"
              cliProjectKey: "$(Sonar-Projectkey)"
              cliProjectName: "$(Sonar-Projectname)"
              cliSources: "."

          - task: SonarCloudAnalyze@3
            displayName: "Run SonarCloud Analysis"

          - task: SonarCloudPublish@3
            displayName: "Publish Quality Gate"
            inputs:
              pollingTimeoutSec: "300"

          - task: Bash@3
            condition: and(succeeded(), ${{ parameters.remove_image_container }})
            displayName: "Stop and remove comtainers"
            inputs:
              targetType: "inline"
              script: |
                docker compose -f docker-compose.yaml -p nikhil-shop down --rmi all

          - task: DockerCompose@1
            condition: and(succeeded(), ${{ parameters.docker_compose }})
            displayName: "Docker Compose Up"
            inputs:
              dockerComposeFile: "**/docker-compose.yaml"
              action: "run services"
              detached: true
              buildImages: true
              projectName: "nikhil-shop"

          - task: Bash@3
            displayName: "Trivy Scan Docker Images"
            inputs:
              targetType: "inline"
              script: |
                SERVICES="cart-service main-service order-service product-service user-service"

                mkdir -p trivy-reports

                for SERVICE in $SERVICES
                do
                  IMAGE="nikhil-shop-$SERVICE:$(IMAGE_TAG)"

                  echo "==================================="
                  echo "Scanning $IMAGE"
                  echo "==================================="

                  trivy image \
                    --severity HIGH,CRITICAL \
                    --ignore-unfixed \
                    --format table \
                    --output trivy-reports/$SERVICE.txt \
                    "$IMAGE"
                  done

          - task: PublishBuildArtifacts@1
            displayName: "Publish Trivy Reports"
            inputs:
              pathtoPublish: "trivy-reports"
              ArtifactName: "Trivy-Reports"

          - script: |
              export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
              export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
              export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
              aws sts get-caller-identity
            displayName: "Verify AWS Credentials"

          # - script: |
          #   displayName:  'Login to Amazon ECR'