name: Nikhil-Shop-Pipeline

env:
  NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Nikhil-Shop
    runs-on: self-hosted

    steps:
      - name: Git-checkout
        uses: actions/checkout@v6
        
      - name: Setup Node
        uses:  actions/setup-node@v6
        with:
          node-version: '22'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Application
        run: npm run build 

      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: |
            npx sonar-scan \
            -Dsonar.projectKey=${{ SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ SONAR_HOST_URL }}
            -Dsonar.token=${{ SONAR_TOKEN }}


      