name: Nikhil-Shop-Pipeline

on:
  push:
    branch:
      - main

jobs:
  build:
    name: Nikhil-Shop
    runs-on: self-hosted

    steps:
      - name: Git-checkout
        uses: actions/checkout@v6
        
      - name: Setup Node
        uses:  actions/setup-node@v6
        with:
          node-version: '22'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Application
        run: npm run build 
