name: Nikhil-Shop-Pipeline

env:
  NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

on:
  push:
    branch:
      - main

jobs:
  build:
    name: Nikhil-Shop
    runs-on: self-hosted

    steps:
      - name: Git-checkout
        uses: actions/checkout@v6
        
      - name: Setup Node
        uses:  actions/setup-node@v6
        with:
          node-version: '22'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Application
        run: npm run build 

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'


      - name: Download OWASP Dependency Check
        run: |
          VERSION=12.2.2
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip
          unzip dependency-check-${VERSION}-release.zip

      - name: Run OWASP Scan
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "Nikhil-Shop" \
            --scan . \
            --format HTML \
            --out reports

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Report
          path: reports
